/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE markBaseService PLEASE EDIT ../mark.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Mark } from '../../domain/school-app_db/mark';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Mark.service.ts
 */

/*
 * SCHEMA DB Mark
 *
	{
		Mark: {
			type: 'Decimal'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		_student: {
			type: Schema.ObjectId,
			ref : "Mark"
		},
	}
 *
 */
@Injectable()
export class MarkBaseService {

    contextUrl: string = environment.endpoint + '/mark';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * MarkService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Mark): Observable<Mark> {
        return this.http
            .post<Mark>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * MarkService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * MarkService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Mark> {
        return this.http
            .get<Mark>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * MarkService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Mark[]> {
        return this.http
            .get<Mark[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * MarkService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Mark): Observable<Mark> {
        return this.http
            .post<Mark>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
